name: Coverage
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
permissions:
  contents: read
jobs:
  build:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true

      - name: Generate unit test coverage
        run: make coverage-unit

      - name: Check unit test coverage
        uses: vladopajic/go-test-coverage@f94bcf0d6b9fa5fb8b783830b22648f6c17475e2 # v2.19.0
        with:
          # Configure action using config file (option 1)
          config: ./.testcoverage.yml
          
          # Configure action by specifying input parameters individually (option 2).
          # If you are using config file (option 1) you shouldn't use these parameters, however
          # specifing these action parameters will override appropriate config values.
          profile: coverage.out
          local-prefix: github.com/Peersyst/xrpl-go
          threshold-file: 0
          threshold-package: 0
          threshold-total: 0
