name: Release
on:
  workflow_dispatch:
    inputs:
      commit_branch:
        description: The branch or the commit sha to push tag to
        required: true
      tag:
        description: The tag of the release
        required: true
      is_pre_release:
        description: Is this a pre-release?
        type: boolean
        required: true
permissions:
  contents: read
jobs:
  release:
    runs-on: ubuntu-latest
    name: Release
    permissions:
      contents: write # to create the git tag and publish the GitHub release
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event.inputs.commit_branch }}
          fetch-depth: 0
          fetch-tags: true
      - name: Publish the Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          tag_name: ${{ github.event.inputs.tag }}
          prerelease: ${{ github.event.inputs.is_pre_release }}
          target_commitish: ${{ github.event.inputs.commit_branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
